### ISSUE TITLE
User Story: Create Account 

### ISSUE THREAD

**Issue by IGramajoO** [rltsystems/Group5_CST438_Project02#1]
As a user, I want to be able to create an account, so I can make use of the website

**Comment by rltsystems** [comment]
This looks great. I created a front-end issue for the same label.
We may want to go into detail about input validation/tests for the Username and Password Fields.

i.e. Username - Check if username exists, Use only alphanumeric characters [0-9][a-Z], Password, and Confirm Password match etc.
